// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gh.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmploymentType int32

const (
	EmploymentType_WORK       EmploymentType = 0
	EmploymentType_OPENSOURCE EmploymentType = 1
	EmploymentType_HOBBY      EmploymentType = 2
)

var EmploymentType_name = map[int32]string{
	0: "WORK",
	1: "OPENSOURCE",
	2: "HOBBY",
}

var EmploymentType_value = map[string]int32{
	"WORK":       0,
	"OPENSOURCE": 1,
	"HOBBY":      2,
}

func (x EmploymentType) String() string {
	return proto.EnumName(EmploymentType_name, int32(x))
}

func (EmploymentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_22afb19a307f14c9, []int{0}
}

type OwnProfileRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OwnProfileRequest) Reset()         { *m = OwnProfileRequest{} }
func (m *OwnProfileRequest) String() string { return proto.CompactTextString(m) }
func (*OwnProfileRequest) ProtoMessage()    {}
func (*OwnProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22afb19a307f14c9, []int{0}
}

func (m *OwnProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnProfileRequest.Unmarshal(m, b)
}
func (m *OwnProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnProfileRequest.Marshal(b, m, deterministic)
}
func (m *OwnProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnProfileRequest.Merge(m, src)
}
func (m *OwnProfileRequest) XXX_Size() int {
	return xxx_messageInfo_OwnProfileRequest.Size(m)
}
func (m *OwnProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OwnProfileRequest proto.InternalMessageInfo

func (m *OwnProfileRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type OwnProfileResponse struct {
	ContributionsDispersion float32        `protobuf:"fixed32,1,opt,name=contributionsDispersion,proto3" json:"contributionsDispersion,omitempty"`
	Type                    EmploymentType `protobuf:"varint,2,opt,name=type,proto3,enum=pb.EmploymentType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}       `json:"-"`
	XXX_unrecognized        []byte         `json:"-"`
	XXX_sizecache           int32          `json:"-"`
}

func (m *OwnProfileResponse) Reset()         { *m = OwnProfileResponse{} }
func (m *OwnProfileResponse) String() string { return proto.CompactTextString(m) }
func (*OwnProfileResponse) ProtoMessage()    {}
func (*OwnProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22afb19a307f14c9, []int{1}
}

func (m *OwnProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnProfileResponse.Unmarshal(m, b)
}
func (m *OwnProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnProfileResponse.Marshal(b, m, deterministic)
}
func (m *OwnProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnProfileResponse.Merge(m, src)
}
func (m *OwnProfileResponse) XXX_Size() int {
	return xxx_messageInfo_OwnProfileResponse.Size(m)
}
func (m *OwnProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OwnProfileResponse proto.InternalMessageInfo

func (m *OwnProfileResponse) GetContributionsDispersion() float32 {
	if m != nil {
		return m.ContributionsDispersion
	}
	return 0
}

func (m *OwnProfileResponse) GetType() EmploymentType {
	if m != nil {
		return m.Type
	}
	return EmploymentType_WORK
}

func init() {
	proto.RegisterEnum("pb.EmploymentType", EmploymentType_name, EmploymentType_value)
	proto.RegisterType((*OwnProfileRequest)(nil), "pb.OwnProfileRequest")
	proto.RegisterType((*OwnProfileResponse)(nil), "pb.OwnProfileResponse")
}

func init() {
	proto.RegisterFile("gh.proto", fileDescriptor_22afb19a307f14c9)
}

var fileDescriptor_22afb19a307f14c9 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcb, 0x4b, 0xc3, 0x40,
	0x10, 0xc6, 0x9b, 0xd8, 0x4a, 0x3b, 0x87, 0x90, 0x0e, 0x3e, 0x8a, 0xa7, 0x92, 0x83, 0x54, 0x0f,
	0x11, 0x2a, 0x82, 0xd7, 0x46, 0x83, 0x15, 0xc1, 0x94, 0xad, 0x0f, 0xf4, 0xe6, 0x96, 0xa9, 0x2e,
	0xa6, 0x3b, 0xeb, 0xee, 0xb6, 0x92, 0xff, 0x5e, 0x6c, 0x0e, 0xbe, 0xf0, 0x38, 0xdf, 0x37, 0xc3,
	0xf0, 0xfb, 0x41, 0xfb, 0xf9, 0x25, 0x35, 0x96, 0x3d, 0x63, 0x68, 0x64, 0x72, 0x00, 0xdd, 0xe2,
	0x5d, 0x4f, 0x2c, 0xcf, 0x55, 0x49, 0x82, 0xde, 0x96, 0xe4, 0x3c, 0x6e, 0x41, 0xcb, 0xf3, 0x2b,
	0xe9, 0x5e, 0xd0, 0x0f, 0x06, 0x1d, 0x51, 0x0f, 0xc9, 0x0a, 0xf0, 0xfb, 0xaa, 0x33, 0xac, 0x1d,
	0xe1, 0x29, 0xec, 0xce, 0x58, 0x7b, 0xab, 0xe4, 0xd2, 0x2b, 0xd6, 0xee, 0x5c, 0x39, 0x43, 0xd6,
	0x29, 0xae, 0xaf, 0x43, 0xf1, 0x5f, 0x8d, 0xfb, 0xd0, 0xf4, 0x95, 0xa1, 0x5e, 0xd8, 0x0f, 0x06,
	0xd1, 0x10, 0x53, 0x23, 0xd3, 0x7c, 0x61, 0x4a, 0xae, 0x16, 0xa4, 0xfd, 0x4d, 0x65, 0x48, 0xac,
	0xfb, 0xc3, 0x13, 0x88, 0x7e, 0xe6, 0xd8, 0x86, 0xe6, 0x7d, 0x21, 0xae, 0xe2, 0x06, 0x46, 0x00,
	0xc5, 0x24, 0xbf, 0x9e, 0x16, 0xb7, 0xe2, 0x2c, 0x8f, 0x03, 0xec, 0x40, 0x6b, 0x5c, 0x64, 0xd9,
	0x43, 0x1c, 0x0e, 0xef, 0xa0, 0x7b, 0x31, 0x1e, 0xe9, 0xa7, 0xb2, 0x72, 0xca, 0x4d, 0xc9, 0xae,
	0xd4, 0x8c, 0x70, 0x04, 0xd1, 0x17, 0xc3, 0xa5, 0x9e, 0x33, 0x6e, 0x7f, 0xfe, 0xfd, 0xa3, 0x60,
	0x6f, 0xe7, 0x77, 0x5c, 0xe3, 0x26, 0x8d, 0xac, 0xf5, 0xb8, 0x71, 0x64, 0xa4, 0xdc, 0x5c, 0x3b,
	0x3c, 0xfe, 0x08, 0x00, 0x00, 0xff, 0xff, 0xe7, 0xeb, 0x0e, 0xc2, 0x4f, 0x01, 0x00, 0x00,
}
