// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.12.4
// source: gh.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	GHAnalysisService_OwnProfileInfo_FullMethodName = "/pb.GHAnalysisService/OwnProfileInfo"
)

// GHAnalysisServiceClient is the client API for GHAnalysisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GHAnalysisServiceClient interface {
	OwnProfileInfo(ctx context.Context, in *OwnProfileRequest, opts ...grpc.CallOption) (*OwnProfileResponse, error)
}

type gHAnalysisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGHAnalysisServiceClient(cc grpc.ClientConnInterface) GHAnalysisServiceClient {
	return &gHAnalysisServiceClient{cc}
}

func (c *gHAnalysisServiceClient) OwnProfileInfo(ctx context.Context, in *OwnProfileRequest, opts ...grpc.CallOption) (*OwnProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OwnProfileResponse)
	err := c.cc.Invoke(ctx, GHAnalysisService_OwnProfileInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GHAnalysisServiceServer is the server API for GHAnalysisService service.
// All implementations must embed UnimplementedGHAnalysisServiceServer
// for forward compatibility
type GHAnalysisServiceServer interface {
	OwnProfileInfo(context.Context, *OwnProfileRequest) (*OwnProfileResponse, error)
	mustEmbedUnimplementedGHAnalysisServiceServer()
}

// UnimplementedGHAnalysisServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGHAnalysisServiceServer struct {
}

func (UnimplementedGHAnalysisServiceServer) OwnProfileInfo(context.Context, *OwnProfileRequest) (*OwnProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OwnProfileInfo not implemented")
}
func (UnimplementedGHAnalysisServiceServer) mustEmbedUnimplementedGHAnalysisServiceServer() {}

// UnsafeGHAnalysisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GHAnalysisServiceServer will
// result in compilation errors.
type UnsafeGHAnalysisServiceServer interface {
	mustEmbedUnimplementedGHAnalysisServiceServer()
}

func RegisterGHAnalysisServiceServer(s grpc.ServiceRegistrar, srv GHAnalysisServiceServer) {
	s.RegisterService(&GHAnalysisService_ServiceDesc, srv)
}

func _GHAnalysisService_OwnProfileInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OwnProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GHAnalysisServiceServer).OwnProfileInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GHAnalysisService_OwnProfileInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GHAnalysisServiceServer).OwnProfileInfo(ctx, req.(*OwnProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GHAnalysisService_ServiceDesc is the grpc.ServiceDesc for GHAnalysisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GHAnalysisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GHAnalysisService",
	HandlerType: (*GHAnalysisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OwnProfileInfo",
			Handler:    _GHAnalysisService_OwnProfileInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gh.proto",
}
